### ISSUE TITLE
scan code should ignore all files already in .gitignore

### ISSUE THREAD

**Issue by rabbah** [apache/incubator-openwhisk-utilities#39]
scan code does not read .gitignore and so it will scan and apply the constraints to file that aren't intended for a commit.

**Comment by csantanapr** [comment]
This will be a great benefit to have.
For example today I was working with openwhisk-runtime-go repo and I need to exclude `.gogradle` and `vendor` directories which both are already ignored in `.gitignore`

maybe implementing a flag to pass the location of the .igtignore file `--ignore $ROOTDIR/.gitignore`

**Comment by rabbah** [comment]
Prototyped here: https://github.com/apache/incubator-openwhisk-utilities/compare/master...rabbah:gitignore?expand=1

you can pass `--gitignore file` to scancode. I'm using https://github.com/cpburnz/python-path-specification to handle the exclusion matching which means there would be a new dependence to run scancode `pip install pathspec`.

**Comment by csantanapr** [comment]
PRs Welcome !
