### ISSUE TITLE
ASFMinifiedLicenseHeader is missing in scancode folder

### ISSUE THREAD

**Issue by houshengbo** [apache/incubator-openwhisk-utilities#5]
scanCode.cfg looks for ASFMinifiedLicenseHeader, but this header does not exist in scancode folder

**Comment by mrutkows** [comment]
@houshengbo I will submit a PR to scancode in utilities project today.  It was something I meant to do, but had forgotten and got ahead of myself in PRs here...

**Comment by mrutkows** [comment]
Fixed... https://github.com/apache/incubator-openwhisk-utilities/pull/6
